### ISSUE TITLE
Gaat alles op tijd klaar zijn?

### ISSUE THREAD

**Issue by IngeMarieke** [Lkeurentjes/alvtest#2]
mijn plannings vraag is:

Gaat alles op tijd klaar zijn?

**Comment by IngeMarieke** [comment]
Waarschijnlijk

**Comment by IngeMarieke** [comment]
Echt?

**Comment by IngeMarieke** [comment]
> Echt?

Ja

**Comment by Lkeurentjes** [comment]
We hebben het met hele bouwteam over de planning gehad en zijn gezamelijk tot de conclusie gekomen dat dit een realaistische deadline is!
